name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: "true"
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Publish
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}